var Templates = {};

Templates.members = [
    '{{#if members}}',
    '{{#each members}}',
    '<div class="row">',
        '<div class="col-xs-12 col-sm-6 col-md-3">',
            '<h3><b>{{ name }}</b></h3>',
            '{{#if position}} <h4>{{ position }}</h4> {{/if}}',
            '{{#if joined}} <h4>Member since {{ joined }}</h4> {{/if}}',
        '</div>',
        '<div class="col-xs-12 col-sm-6 col-md-3">',
            '{{#if image}} <img alt={{name}} src="images/{{image}}" height="120px"> {{/if}}',
        '</div>',
        '<div class="col-xs-12 col-md-6">',
            '<p>{{ description }}</h4>',
            '{{#if posts}}',
            '<h4>Blog posts:</h4>',
                '<ul style="list-style-type:disc">',
                    '{{#each posts}}',
                    '<li><a href="{{link}}">{{title}}</a></li>',
                    '{{/each}}',
                '</ul>',
            '{{/if}}',
        '</div>',
    '</div>',
    '<hr>',
    '{{/each}}',
    '{{else}}',
        '<span>No members found.</span>',
    '{{/if}}',
].join('\n');
